apiVersion: v1
kind: PersistentVolume
metadata:
  name: pan-pv
spec:
  capacity:
    storage: 5Gi

  accessModes:
    - ReadWriteMany   # ✅ 支持多副本共享

  persistentVolumeReclaimPolicy: Retain

  hostPath:
    path: /opt/www/html   # ⚠️ 先用这个，后面可以换 NFS
