apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pan-pvc
  namespace: pan
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 15Gi
