apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pan-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany

  resources:
    requests:
      storage: 5Gi

  volumeName: pan-pv
