apiVersion: ceph.rook.io/v1
kind: CephFilesystem
metadata:
  name: panfs
  namespace: rook-ceph
spec:
  # Replication size 3 is the usual HA starting point.
  # If your Ceph cluster does not yet have 3 OSD hosts, lower this temporarily.
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - name: replicated
      replicated:
        size: 3
  preserveFilesystemOnDelete: true
  metadataServer:
    activeCount: 1
    activeStandby: true
